import ctypes
import cv2
ctypes.windll.shcore.SetProcessDpiAwareness(1)
ctypes.windll.shcore.SetProcessDpiAwareness(1)
from tkinter import *
from PIL import ImageTk,Image
from tkinter import ttk
Window = Tk()
Window.geometry("900x900")
Window.resizable(0,0)
Window.title("Medicine Vending Machine")
Window.iconbitmap("C:/Users/ginge/Desktop/Plus.ico.ico")
Male=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/male.jpg")).resize((130,130)))
Female=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Female.jpg")).resize((130,130)))
Skin=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Skin.jpg")).resize((185,185)))
Pain=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/pain.jpg")).resize((185,185)))
Vomiting=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Vomiting.jpg")).resize((185,185)))
Cough=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Cough.jpg")).resize((185,185)))
Tooth=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Tooth.jpg")).resize((185,185)))
Heart=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Heart.jpg")).resize((185,185)))
Unconscious=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Unconscious.jpg")).resize((300,160)))
Vision=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Vision.jpg")).resize((185,185)))
Pregnant=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Pregnant.jpg")).resize((185,185)))
Cycle=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Cycle.jpg")).resize((185,185)))
Face=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Face.jpg")).resize((300,195)))
Arm=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Arm.jpg")).resize((230,230)))
Back=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Back.jpg")).resize((230,230)))
Full=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Full.jpg")).resize((200,250)))
Question=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Question.png")).resize((210,195)))
Clock=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Clock.png")).resize((150,150)))
Vitiligo=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Vitiligo.jpg")).resize((200,300)))
Psoriasis=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/psoriasis.jpg")).resize((400,210)))
Eczema=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/eczema.jpg")).resize((310,290)))
Acne=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Acne.jpg")).resize((350,300)))
Razor=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Razor.jpg")).resize((300,250)))
Photosensitive=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Photosensitive.jpg")).resize((300,260)))
Hives=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Raised.png")).resize((300,180)))
Pus=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Pus.jpeg")).resize((300,250)))
Ring=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/actinic.jpg")).resize((300,250)))
Herpes=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Herpes.jpg")).resize((300,250)))
Folliculitis=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Folliculitis.jpg")).resize((270,270)))
Camera=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Camera.jpg")).resize((200,200)))
Diagnosis=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Documents/PROGRAMMING/Python/Diagnosis.jpg")).resize((150,150)))
Eucerin=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Eucerin.jpg")).resize((200,200)))
Twenty=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Twenty.jpg")).resize((400,150)))
def Check(flag,VLT):
    string =""
    string = VLT.get(1.0,END)
    if not(string.startswith("1")):
        flag = 1
    FirstLayer(flag)
def Insertpic():
    global Diagnosis
    Diagnosis=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Documents/PROGRAMMING/Python/Diagnosis.jpg")).resize((550,400)))
def TwelvthLayer():
    for widget in Window.winfo_children():
        widget.destroy() 
    EL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,anchor = CENTER)
    EL1.pack()
    EL2 = Label(Window,text = "   ",pady = 25)
    EL2.pack()
    EL3 = Label(Window,text = "Please Collect The Medicine.\n\n\nThank you!",font = ("",15,""))
    EL3.pack()
    EL2 = Label(Window,text = "   ",pady = 10)
    EL2.pack()
    EB1 = Button(Window,text = "Okay",font = ("",10,"bold"),width = 10,command = Home)
    EB1.pack()
    FL10 = Label(Window,text = "\n\n\n\n\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""))
    FL10.pack(side = BOTTOM)
def EleventhWindow():
    for widget in Window.winfo_children():
        widget.destroy() 
    EL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,anchor = CENTER)
    EL1.pack()
    EL2 = Label(Window,text = "   ")
    EL2.pack()
    EL3 = Label(Window,text = "\nPayment: \nPlease Enter a Twenty Rupee note inside the slot",font = ("",13,"italic"))
    EL3.pack()
    EL5 = Label(Window,text = "   ")
    EL5.pack()
    EL4 = Label(Window,image = Twenty)
    EL4.pack()
    EL6 = Label(Window,text = "   ")
    EL6.pack()
    EB1 = Button(Window,text = "Cancel",font = ("",10,"bold"),width = 10,command = Home)
    EB1.pack()
    EL10 = Label(Window,text = "\n\n\n\n\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""))
    EL10.pack(side = BOTTOM)
    Window.after(5000,TwelvthLayer)
def TenthLayer():
    for widget in Window.winfo_children():
        widget.destroy() 
    NL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,anchor = CENTER)
    NL1.pack()
    NL2 = Label(Window,text = "   ")
    NL2.pack()
    NL3 = Label(Window,text = "Based on your Testimony and the AI scan, \nyou are most likely to be suffering from",font = ("",13,"italic"))
    NL3.pack()
    NL4 = Label(Window,text = "Eczema",font = ("",13,"bold"))
    NL4.pack()
    NL6 = Label(Window,text = "   ")
    NL6.pack()
    NL5 = Label(Window,text = "The Following medicines are prescribed for your Condition:",font = ("",13,"italic"))
    NL5.pack()
    NL8 = Label(Window,text = "   ")
    NL8.pack()
    NL4 = Label(Window,image = Eucerin)
    NL4.pack()
    NL7 = Label(Window,text = "   ")
    NL7.pack()
    NL11 = Label(Window,text = "Eucerin",font = ("",13,"bold"))
    NL11.pack()
    NL9 = Label(Window,text = "Apply Once Regularly in affected region. \nFirst Results are seen after two weeks.",font = ("",10,"italic"))
    NL9.pack()
    TL8 = Label(Window,text = "   ")
    TL8.pack()
    TB1 = Button(Window,text = "Buy for ₹20.00",width =15,font=("",13,"bold"),command = EleventhWindow)
    TB1.pack()
    TL7 = Label(Window,text = "   ")
    TL7.pack()
    TB2 = Button(Window,text = "Cancel",width =15,font=("",13,"bold"),command = Home)
    TB2.pack()
    #NL10 = Label(Window,text = "\n\n\n\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""))
    #NL10.pack(side = BOTTOM)
def NinthLayer():
    for widget in Window.winfo_children():
        widget.destroy() 
    NL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,anchor = CENTER)
    NL1.pack()
    NL2 = Label(Window,text = "   ",pady = 25)
    NL2.pack()
    NL3 = Label(Window,text = "The AI database scan is finished",font = ("",13,"italic"))
    NL3.pack()
    NL2 = Label(Window,text = "   ")
    NL2.pack()
    NL3 = Label(Window,text = "Do you remember your parents or Grandparents having skin issues?",font = ("",10,""))
    NL3.pack()
    NL4 = Label(Window,text = "   ")
    NL4.pack()
    NB1 = Button(Window,text = "Yes",width =10,font=("",10,"bold"),command = TenthLayer)
    NB1.pack()
    NL5 = Label(Window,text = "   ")
    NL5.pack()
    NB2 = Button(Window,text = "No",width =10,font=("",10,"bold"),command = TenthLayer)
    NB2.pack()
    NL6 = Label(Window,text = "   ")
    NL6.pack()
    FL10 = Label(Window,text = "\n\n\n\n\n\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""))
    FL10.pack(side = BOTTOM)
def EighthWindow():
    #Window = Tk()
    for widget in Window.winfo_children():
        widget.destroy() 
    Insertpic()
    sL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,anchor = CENTER)
    sL1.pack()
    sL2 = Label(Window,text = "   ")
    sL2.pack()
    sL3 = Label(Window,text = "This is your Captured Photograph",font = ("",12,"italic"),pady=25)
    sL3.pack()
    sL4 = Label(Window,image = Diagnosis)
    sL4.pack()
    sL5 = Label(Window,text = "   ")
    sL5.pack()
    sB1 = Button(Window,text = "Proceed for AI confirmation",font = ("",10,"bold"),command = NinthLayer)
    sB1.pack()
    sL5 = Label(Window,text = "   ")
    sL5.pack()
    sL6 = Button(Window,text = "Cancel",width = 10,font = ("",10,"bold"),command = Home)
    sL6.pack()
def SeventhLayer():
    #Window.destroy()
    cam = cv2.VideoCapture(0)

    # let's assume the number of images gotten is 0
    img_counter = 0

    # while loop
    while True:
        # intializing the frame, ret
        ret,frame = cam.read()
        # if statement
        if not ret:
            print('failed to grab frame')
            break
        # the frame will show with the title of test
        cv2.imshow('Press Spacebar to Capture', frame)
        #to get continuous live video feed from my laptops webcam
        k  = cv2.waitKey(1)
        # if the escape key is been pressed, the app will stop
        if k%256 == 27:
            #EighthWindow()
            print('escape hit, closing the app')
            break
        # if the spacebar key is been pressed
        # screenshots will be taken
        elif k%256  == 32:
            # the format for storing the images scrreenshotted
            img_name = f'opencv_frame_{img_counter}.png'
            # saves the image as a png file
            cv2.imwrite("Diagnosis.jpg", frame)
            #Diagnosis=ImageTk.PhotoImage((Image.open("C:/Users/ginge/Desktop/Diagnosis.jpg")).resize((150,150)))
            print('screenshot taken')
            # the number of images automaticallly increases by 1
            img_counter += 1
    cam.release() 
    #cam.destoryAllWindows()
    EighthWindow()
def SixthLayer():
    for widget in Window.winfo_children():
        widget.destroy() 
    sL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,padx = 165,anchor = CENTER)
    sL1.pack()
    sL2 = Label(Window,text = "   ")
    sL2.pack()
    sL7 = Label(Window,image = Camera)
    sL7.pack()
    sL3 = Label(Window,text = "Would you like to upload a picture for Better Confirmation?",font = ("",12,"italic"),pady=25)
    sL3.pack()
    sL4 = Label(Window,text = "   ")
    sL4.pack()
    sB1 = Button(Window,text = "Yes",width =10,font=("",10,"bold"),command = SeventhLayer)
    sB1.pack()
    sL5 = Label(Window,text = "   ")
    sL5.pack()
    sB2 = Button(Window,text = "No",width =10,font=("",10,"bold"),command = NinthLayer)
    sB2.pack()
    sL6 = Label(Window,text = "   ")
    sL6.pack()
    sB3 = Button(Window,text = "Cancel",width = 10,font = ("",10,"bold"),command = Home)
    sB3.pack()
    FL10 = Label(Window,text = "\n\n\n\n\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""),pady = 50)
    FL10.pack(side = BOTTOM)
def FifthLayer():
    for widget in Window.winfo_children():
        widget.destroy()  
    main_frame = Frame(Window)
    main_frame.pack(fill = BOTH, expand = 1)
    my_canvas = Canvas(main_frame)
    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
    my_scrollbar = ttk.Scrollbar(main_frame, orient = VERTICAL, command = my_canvas.yview)
    my_scrollbar.pack(side = RIGHT, fill = Y)
    my_canvas.configure(yscrollcommand = my_scrollbar.set)
    my_canvas.bind('<Configure>', lambda e: my_canvas.configure(scrollregion = my_canvas.bbox("all")))
    second_frame = Frame(my_canvas)
    my_canvas.create_window((0,0), window = second_frame, anchor = "nw")
    TL1 = Label(second_frame,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,padx = 165,anchor = CENTER)
    TL1.pack()
    TL2 = Label(second_frame,text = "   ")
    TL2.pack()
    TL3 = Label(second_frame,text = "How does the skin problem look like:",font = ("",12,"italic"),pady=25)
    TL3.pack()
    TL4 = Label(second_frame,image = Vitiligo)
    TL4.pack()
    TLB1 = Button(second_frame,text = "Discolouration of the skin?",width = 40,font=("",10,"bold"))
    TLB1.pack()
    TL2 = Label(second_frame,text = "   ")
    TL2.pack()
    TL5 = Label(second_frame,image = Psoriasis)
    TL5.pack()
    TLB2 = Button(second_frame,text = "Scaly itchy skin around the neck or forehead?",width = 40,font=("",10,"bold"))
    TLB2.pack()
    TL6 = Label(second_frame,text = "   ")
    TL6.pack()
    TL7 = Label(second_frame,image = Eczema)
    TL7.pack()
    TLB3 = Button(second_frame,text = "Red or Purple itchy patches?",width = 40,font=("",10,"bold"),command = SixthLayer)
    TLB3.pack()
    TL8 = Label(second_frame,text = "   ")
    TL8.pack()
    TL9 = Label(second_frame,image = Acne)
    TL9.pack()  
    TLB4 = Button(second_frame,text = "Round Pink raised spots?",width = 40,font=("",10,"bold"))
    TLB4.pack()
    TL10 = Label(second_frame,text = "   ")
    TL10.pack()
    TL11 = Label(second_frame,image = Razor)
    TL11.pack()
    TLB5 = Button(second_frame,text = "Bumps right after shaving in the beard area?",width = 40,font=("",10,"bold"))
    TLB5.pack()
    TL12 = Label(second_frame,text = "   ")
    TL12.pack()
    TL13 = Label(second_frame,image = Photosensitive)
    TL13.pack()
    TLB6 = Button(second_frame,text = "Does it happen on a hot sunny day?",width = 40,font=("",10,"bold"))
    TLB6.pack()
    TL14 = Label(second_frame,text = "   ")
    TL14.pack()
    TL15 = Label(second_frame,image = Hives)
    TL15.pack()
    TLB7 = Button(second_frame,text = "Is the skin raised in Patches and Itch?",width = 40,font=("",10,"bold"))
    TLB7.pack()
    TL16 = Label(second_frame,text = "   ")
    TL16.pack()
    TL17 = Label(second_frame,image = Pus)
    TL17.pack()
    TLB8 = Button(second_frame,text = "A Big red growing bump with yellow fluid?",width = 40,font=("",10,"bold"))
    TLB8.pack()
    TL16 = Label(second_frame,text = "   ")
    TL16.pack()
    TL17 = Label(second_frame,image = Ring)
    TL17.pack()
    TLB8 = Button(second_frame,text = "A red itchy ring around the neck?",width = 40,font=("",10,"bold"))
    TLB8.pack()
    TL18 = Label(second_frame,text = "   ")
    TL18.pack()
    TL19 = Label(second_frame,image = Herpes)
    TL19.pack()
    TLB9 = Button(second_frame,text = "Blister like sores?",width = 40,font=("",10,"bold"))
    TLB9.pack()
    TL20 = Label(second_frame,text = "   ")
    TL20.pack()
    TL21 = Label(second_frame,image = Folliculitis)
    TL21.pack()
    TLB10 = Button(second_frame,text = "Hair roots inflamed?",width = 40,font=("",10,"bold"))
    TLB10.pack()
    TLB11 = Button(Window,text = "Cancel",width =10,font=("",10,"bold"), command = Home)
    TLB11.pack()
def FourthLayer():
    for widget in Window.winfo_children():
        widget.destroy() 
    FL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,anchor = CENTER)
    FL1.pack()
    FL2 = Label(Window,text = "   ")
    FL2.pack()
    FL8 = Label(Window,image = Clock)
    FL8.pack()
    FL3 = Label(Window,text = "For How long is it happening on your Face or Neck?:",font = ("",12,"italic"),pady=25)
    FL3.pack()
    FLB1 = Button(Window,text = "A Long time - more than an year?",width = 40,font=("",10,"bold"),command = FifthLayer)
    FLB1.pack()
    FL2 = Label(Window,text = "   ")
    FL2.pack()
    FLB2 = Button(Window,text = "A Very long time - more than 5 years?",width = 40,font=("",10,"bold"),command = FifthLayer)
    FLB2.pack()
    FL6 = Label(Window,text = "   ")
    FL6.pack()
    FLB3 = Button(Window,text = "It Started a few days ago",width = 40,font=("",10,"bold"),command = FifthLayer)
    FLB3.pack() 
    FL7 = Label(Window,text = "   ")
    FL7.pack()  
    FLB4 = Button(Window,text = "Its been happening for a few months",width = 40,font=("",10,"bold"),command = FifthLayer)
    FLB4.pack() 
    FL9 = Label(Window,text = "   ")
    FL9.pack()   
    TLB8 = Button(Window,text = "Cancel",width =10,font=("",10,"bold"), command = Home)
    TLB8.pack()
    FL10 = Label(Window,text = "\n\n\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""),pady = 50)
    FL10.pack(side = BOTTOM)
def ThirdLayer():
    for widget in Window.winfo_children():
        widget.destroy() 
    main_frame = Frame(Window)
    main_frame.pack(fill = BOTH, expand = 1)
    my_canvas = Canvas(main_frame)
    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
    my_scrollbar = ttk.Scrollbar(main_frame, orient = VERTICAL, command = my_canvas.yview)
    my_scrollbar.pack(side = RIGHT, fill = Y)
    my_canvas.configure(yscrollcommand = my_scrollbar.set)
    my_canvas.bind('<Configure>', lambda e: my_canvas.configure(scrollregion = my_canvas.bbox("all")))
    second_frame = Frame(my_canvas)
    my_canvas.create_window((0,0), window = second_frame, anchor = "nw")
    TL1 = Label(second_frame,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,padx = 165,anchor = CENTER)
    TL1.pack()
    TL2 = Label(second_frame,text = "   ")
    TL2.pack()
    TL3 = Label(second_frame,text = "On Which Body Part is your Skin Problem occuring?:",font = ("",12,"italic"),pady=25)
    TL3.pack()
    TL4 = Label(second_frame,image = Face)
    TL4.pack()
    TLB1 = Button(second_frame,text = "Is it happening around the Face and Neck?",width = 60,font=("",10,"bold"),command = FourthLayer)
    TLB1.pack()
    TL2 = Label(second_frame,text = "   ")
    TL2.pack()
    TL5 = Label(second_frame,image = Arm)
    TL5.pack()
    TLB2 = Button(second_frame,text = "Is it happening on the arms and legs?",width = 60,font=("",10,"bold"))
    TLB2.pack()
    TL6 = Label(second_frame,text = "   ")
    TL6.pack()
    TL7 = Label(second_frame,image = Back)
    TL7.pack()
    TLB3 = Button(second_frame,text = "Is it happening around the chest or back?",width = 60,font=("",10,"bold"))
    TLB3.pack()
    TL8 = Label(second_frame,text = "   ")
    TL8.pack()
    TL9 = Label(second_frame,image = Full)
    TL9.pack()
    TLB4 = Button(second_frame,text = "Is it happening throughout the body?",width = 60,font=("",10,"bold"))
    TLB4.pack()
    TL10 = Label(second_frame,text = "   ")
    TL10.pack()
    TL11 = Label(second_frame,image = Question)
    TL11.pack()
    TLB5 = Button(second_frame,text = "Is it happening in any other area?",width = 60,font=("",10,"bold"))
    TLB5.pack()
    TLB8 = Button(Window,text = "Cancel",width =10,font=("",10,"bold"), command = Home)
    TLB8.pack()
def SecondLayer(Gender):
    for widget in Window.winfo_children():
        widget.destroy()
    main_frame = Frame(Window)
    main_frame.pack(fill = BOTH, expand = 1)
    my_canvas = Canvas(main_frame)
    my_canvas.pack(side=LEFT, fill=BOTH, expand=1)
    my_scrollbar = ttk.Scrollbar(main_frame, orient = VERTICAL, command = my_canvas.yview)
    my_scrollbar.pack(side = RIGHT, fill = Y)
    my_canvas.configure(yscrollcommand = my_scrollbar.set)
    my_canvas.bind('<Configure>', lambda e: my_canvas.configure(scrollregion = my_canvas.bbox("all")))
    second_frame = Frame(my_canvas)
    my_canvas.create_window((0,0), window = second_frame, anchor = "nw")
    if Gender=="Male" or Gender=="Female":
        SL1 = Label(second_frame,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20,padx = 165,anchor = CENTER)
        SL1.pack()
        SL2 = Label(second_frame,text = "   ")
        SL2.pack()
        SL3 = Label(second_frame,text = "Please Describe Your Symptoms:",font = ("",12,"italic"),pady=25)
        SL3.pack()
        SL4 = Label(second_frame,image = Skin)
        SL4.pack()
        SLB1 = Button(second_frame,text = "Has your Skin changed Colour? Does it itch,hurt?",width = 60,font=("",10,"bold"),command = ThirdLayer)
        SLB1.pack()
        SL2 = Label(second_frame,text = "   ")
        SL2.pack()
        SL5 = Label(second_frame,image = Pain)
        SL5.pack()
        SLB2 = Button(second_frame,text = "Is any part of your body paining?",width = 60,font=("",10,"bold"))
        SLB2.pack()
        SL6 = Label(second_frame,text = "   ")
        SL6.pack()
        SL7 = Label(second_frame,image = Vomiting)
        SL7.pack()
        SLB3 = Button(second_frame,text = "Are you experiencing Stomach pain, Vomiting?",width = 60,font=("",10,"bold"))
        SLB3.pack()
        SL8 = Label(second_frame,text = "   ")
        SL8.pack()
        SL9 = Label(second_frame,image = Cough)
        SL9.pack()
        SLB4 = Button(second_frame,text = "Are you Coughing, Sneezing, or have throat irritation?",width = 60,font=("",10,"bold"))
        SLB4.pack()
        SL10 = Label(second_frame,text = "   ")
        SL10.pack()
        SL11 = Label(second_frame,image = Tooth)
        SL11.pack()
        SLB5 = Button(second_frame,text = "Is it related to your Teeth or Mouth?",width = 60,font=("",10,"bold"))
        SLB5.pack()
        SL10 = Label(second_frame,text = "   ")
        SL10.pack()
        SL11 = Label(second_frame,image = Heart)
        SL11.pack()
        SLB5 = Button(second_frame,text = "Are you experiencing frequent chest pain?",width = 60,font=("",10,"bold"))
        SLB5.pack()
        SL12 = Label(second_frame,text = "   ")
        SL12.pack()
        SL13 = Label(second_frame,image = Unconscious)
        SL13.pack()
        SLB6 = Button(second_frame,text = "Are you facing Fatigue, Unconsciousness, Convulsions?",width = 60,font=("",10,"bold"))
        SLB6.pack()
        SL14 = Label(second_frame,text = "   ")
        SL14.pack()
        SL15 = Label(second_frame,image = Vision)
        SL15.pack()
        SLB7 = Button(second_frame,text = "Are you having issues with Vision, Hearing, or Tasting?",width = 60,font=("",10,"bold"))
        SLB7.pack()
    if Gender=="Female":
        SL14 = Label(second_frame,text = "   ")
        SL14.pack()
        SL15 = Label(second_frame,image = Pregnant)
        SL15.pack()
        SLB7 = Button(second_frame,text = "Are you experiencing trouble in Pregnancy or Maternity?",width = 60,font=("",10,"bold"))
        SLB7.pack()
        SL14 = Label(second_frame,text = "   ")
        SL14.pack()
        SL15 = Label(second_frame,image = Cycle)
        SL15.pack()
        SLB7 = Button(second_frame,text = "Are you experiencing troubles in monthly menstrual cycles",width = 60,font=("",10,"bold"))
        SLB7.pack()
    SLB8 = Button(Window,text = "Cancel",width =10,font=("",10,"bold"), command = Home)
    SLB8.pack()
def FirstLayer(flag):
    if flag==1:
        Verification(1)
    else:
        for widget in Window.winfo_children():
            widget.destroy()    
        FL1 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=20)
        FL1.pack()
        VL3 = Label(Window,text = "   ")
        VL3.pack()
        VL4 = Label(Window,text = "Please select your Gender:",font = ("",12,"italic"),pady=15)
        VL4.pack()
        VL3 = Label(Window,text = "   ")
        VL3.pack()
        VL9 = Label(Window,image = Male)
        VL9.pack()
        VLB1 = Button(Window,text = "Male",width =10,font=("",10,"bold"),command = lambda:SecondLayer("Male"))
        VLB1.pack()
        VL7 = Label(Window,text = "   ")
        VL7.pack()
        VL10 = Label(Window,image = Female)
        VL10.pack()
        VLB2 = Button(Window,text = "Female",width =10,font=("",10,"bold"),command = lambda:SecondLayer("Female"))
        VLB2.pack()
        VL8 = Label(Window,text = "   ")
        VL8.pack()
        VLB3 = Button(Window,text = "Other",width =10,font=("",10,"bold"),command = lambda:SecondLayer("Male"))
        VLB3.pack()
        VL8 = Label(Window,text = "   ")
        VL8.pack()
        VLB4 = Button(Window,text = "Cancel",width =10,font=("",10,"bold"),command = Home)
        VLB4.pack()
        VL11 = Label(Window,text = "\n-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""),pady = 50)
        VL11.pack(side = BOTTOM)
def Verification(glag):
    flag = 0
    Filler = "\n\n\n\n\n\n"
    for widget in Window.winfo_children():
        widget.destroy()
    VL2 = Label(Window,text = "Medicine Dispenser Machine",font = ("",20,"bold"),pady=25)
    VL2.pack()
    VL3 = Label(Window,text = "   ",pady=25)
    VL3.pack()
    VL4 = Label(Window,text = "Please select your ID:",font = ("",12,"italic"),pady=25)
    VL4.pack()
    menu = StringVar()
    menu.set("            Select an ID           ")
    drop= OptionMenu(Window, menu,"Aadhar Card","Voter ID","Driving License","Ration Card","PAN Card")
    drop.pack()
    VL5 = Label(Window,text = "   ",pady=15)
    VL5.pack()
    VL1 = Label(Window,text = "Please Enter a Valid ID Number",font = ("",12,"italic"),pady = 25)
    VL1.pack()
    VLT = Text(Window,height = 1,width = 25)
    VLT.pack()
    VL6 = Label(Window,text = "   ")
    VL6.pack()
    VL8 = Label(Window,text = f"{Filler}-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""),pady = 50)
    if glag==1:
        VL9 = Label(Window,text = "The Entered Id does not match Records! Try Again!",font = ("",12,"italic"),pady = 25)
        VL9.pack()
        VL8.destroy()
        Filler = "\n\n\n"
        VL8 = Label(Window,text = f"{Filler}-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""),pady = 50)
    VLB1 = Button(Window,text = "Verify",width =10,font=("",10,"bold"), command = lambda:Check(flag,VLT))
    VLB1.pack()
    VL7 = Label(Window,text = "   ")
    VL7.pack()
    VLB2 = Button(Window,text = "Cancel",width =10,font=("",10,"bold"), command = Home)
    VLB2.pack()
    VL8.pack(side = BOTTOM)
def Home():
    #Window.configure(bg='')
    for widget in Window.winfo_children():
        widget.destroy()
    WL1 = Label(Window,text = "Welcome to Medicine Dispenser Machine!",font = ("",20,"bold"),pady=25)
    WL1.pack()
    WL8 = Label(Window,text = "Location: Holesamudra Village, Karnataka",font = ("",11,"italic"))
    WL8.pack()
    WL5 = Label(Window,text = "   ",pady = 25)
    WL5.pack()
    WL2 = Label(Window,text = "Please Select your Language:",font = ("",13,""),pady = 50)
    WL2.pack()
    WB1 = Button(Window,text = "English",width = 15,font = ("",11,"bold"), command = lambda: Verification(0))
    WB1.pack()
    WL3 = Label(Window,text = "   ")
    WL3.pack()
    WB2 = Button(Window,text = "ಕನ್ನಡ",width = 15,font = ("",11,"bold"))
    WB2.pack()
    WL4 = Label(Window,text = "   ")
    WL4.pack()
    WB3 = Button(Window,text = "हिन्दी",width = 15,font = ("",11,"bold"))
    WB3.pack()
    WL7 = Label(Window,text = "   ",pady = 90)
    WL7.pack()
    WL6 = Label(Window,text = "-------------------------------------------------------------------------------------------------------------------------------\nQuantumX Hackathon\nTeam Alpha\nAryaman, Joel, Deeksha, Rajeshwari\nAtria Institute of Technology",font = ("Helvetica",11,""),pady = 50)
    WL6.pack(side = BOTTOM)
    Window.mainloop()
Home()